server:
  port: 20000

spring:
  application:
    name: catalog-service
  config:
    import: "configserver:http://127.0.0.1:8888"
  cloud:
    config:
      name: actuator,database,eureka,logging,prometheus,rabbitmq,token,zipkin
  jpa:
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

logging:
  level:
    com.example.catalogservice: DEBUG

catalog:
  consumer:
    group-id: catalogConsumer