spring:
  config:
    import: "configserver:http://127.0.0.1:8888"
  cloud:
    config:
      name: user-service,actuator,eureka,rabbitmq,token

logging:
  level:
    root: INFO
    org.springframework.security: DEBUG  # Spring Security 전체 디버깅
    org.springframework.web: DEBUG       # DispatcherServlet 등 요청 처리
