spring:
  config:
    import: "configserver:http://127.0.0.1:8888"
  cloud:
    config:
      name: user-service,actuator,eureka,rabbitmq,token

logging:
  level:
    org.springframework.web: DEBUG     # 스프링 웹(MVC 포함) 관련 요청 처리
    org.springframework.security: INFO  # 시큐리티 관련 요청 로그
    org.springframework.boot.web: DEBUG # 내장 톰캣 등 서블릿 관련 처리
