server:
  port: 60000

spring:
  application:
    name: user-service
  config:
    import: "configserver:http://127.0.0.1:8888"
  cloud:
    config:
      name: actuator,database,eureka,logging,prometheus,rabbitmq,token,zipkin

greeting:
  message: Welcome to the Simple E-commerce.

gateway:
  ip: localhost

logging:
  level:
    com.example.userservice: DEBUG