server:
  port: 10000

spring:
  application:
    name: order-service
  config:
    import: "configserver:http://127.0.0.1:8888"
  cloud:
    config:
      name: actuator,eureka,rabbitmq,token,logging,zipkin,database

logging:
  level:
    com.example.orderservice: DEBUG