server:
  poer: 8080

spring:
  application:
    name: base-service

eureka:
  client:
    register-with-eurkea: true
    fetch-registry: true
    service-url:
#      defaultZone: http://localhost:8761/eureka
      defaultZone: http://localhost:8762/eureka, http://aunis2-M1.local:8763/eureka
