server:
  port: 8000

spring:
  application:
    name: apigateway-service
  config:
#    import: "configserver:http://127.0.0.1:8888"
    import: "configserver:http://config-service:8888"
  cloud:
    config:
      name: actuator,database,eureka,logging,prometheus,rabbitmq,token,zipkin
    gateway:
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: Spring Cloud Gateway Global Filter
            preLogger: true
            postLogger: true
      routes:
        - id: user-service-public
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/welcome
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
        - id: user-service-auth
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/users,/user-service/login
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/**
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - AuthorizationHeaderFilter
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/order-service/**
            - Method=GET,POST
        - id: catalog-service
          uri: lb://CATALOG-SERVICE
          predicates:
            - Path=/catalog-service/**
            - Method=GET,POST
